### ISSUE TITLE
Content is not populated on parent elements

### ISSUE THREAD

**Issue by Gigabyte5671** [Cascades-CSS/CSS-to-HTML#13]
Content - specifically from the `content` style property - is not populated on parent elements.

### Reproduction
```css
main {
    content: 'A';
}
main section {
    content: 'B';
}
```

The above CSS produces the following HTML:
```html
<main><section>B</section></main>
```

### Expected Result
The above CSS should produce something like this:
```html
<main>A<section>B</section></main>
```
Or this:
```html
<main><section>B</section>A</main>
```
